const express = require("express");
const router = express.Router();
const { authenticate, authorize } = require("../middleware/auth.middleware");

const STUDENTS = [
  {
    IdAlumno: "ALU0001",
    Nombre: "Valentina García",
    Genero: 0,
    Edad: 20,
    AnioIngreso: 2023,
    AyudaFinanciera: 0,
    ColegioTecnico: 0,
    PromedioColegio: 7.8,
  },
  {
    IdAlumno: "ALU0002",
    Nombre: "Luciano Martínez",
    Genero: 1,
    Edad: 22,
    AnioIngreso: 2022,
    AyudaFinanciera: 1,
    ColegioTecnico: 1,
    PromedioColegio: 6.2,
  },
  {
    IdAlumno: "ALU0003",
    Nombre: "Camila López",
    Genero: 0,
    Edad: 19,
    AnioIngreso: 2024,
    AyudaFinanciera: 0,
    ColegioTecnico: 0,
    PromedioColegio: 8.5,
  },
  {
    IdAlumno: "ALU0004",
    Nombre: "Nicolás Fernández",
    Genero: 1,
    Edad: 24,
    AnioIngreso: 2020,
    AyudaFinanciera: 0,
    ColegioTecnico: 1,
    PromedioColegio: 7.1,
  },
  {
    IdAlumno: "ALU0005",
    Nombre: "Sofía Rodríguez",
    Genero: 0,
    Edad: 21,
    AnioIngreso: 2022,
    AyudaFinanciera: 1,
    ColegioTecnico: 0,
    PromedioColegio: 6.8,
  },
  {
    IdAlumno: "ALU0006",
    Nombre: "Matías González",
    Genero: 1,
    Edad: 23,
    AnioIngreso: 2021,
    AyudaFinanciera: 0,
    ColegioTecnico: 0,
    PromedioColegio: 5.9,
  },
  {
    IdAlumno: "ALU0007",
    Nombre: "Agustina Pérez",
    Genero: 0,
    Edad: 20,
    AnioIngreso: 2023,
    AyudaFinanciera: 1,
    ColegioTecnico: 1,
    PromedioColegio: 9.1,
  },
  {
    IdAlumno: "ALU0008",
    Nombre: "Facundo Sánchez",
    Genero: 1,
    Edad: 25,
    AnioIngreso: 2020,
    AyudaFinanciera: 0,
    ColegioTecnico: 0,
    PromedioColegio: 6.4,
  },
  {
    IdAlumno: "ALU0009",
    Nombre: "Lucía Ramírez",
    Genero: 0,
    Edad: 22,
    AnioIngreso: 2022,
    AyudaFinanciera: 0,
    ColegioTecnico: 1,
    PromedioColegio: 8.0,
  },
  {
    IdAlumno: "ALU0010",
    Nombre: "Santiago Torres",
    Genero: 1,
    Edad: 18,
    AnioIngreso: 2024,
    AyudaFinanciera: 1,
    ColegioTecnico: 0,
    PromedioColegio: 7.3,
  },
  {
    IdAlumno: "ALU0011",
    Nombre: "Florencia Álvarez",
    Genero: 0,
    Edad: 26,
    AnioIngreso: 2020,
    AyudaFinanciera: 0,
    ColegioTecnico: 0,
    PromedioColegio: 5.5,
  },
  {
    IdAlumno: "ALU0012",
    Nombre: "Tomás Herrera",
    Genero: 1,
    Edad: 21,
    AnioIngreso: 2022,
    AyudaFinanciera: 1,
    ColegioTecnico: 1,
    PromedioColegio: 7.6,
  },
  {
    IdAlumno: "ALU0013",
    Nombre: "Micaela Castro",
    Genero: 0,
    Edad: 23,
    AnioIngreso: 2021,
    AyudaFinanciera: 0,
    ColegioTecnico: 0,
    PromedioColegio: 6.9,
  },
  {
    IdAlumno: "ALU0014",
    Nombre: "Ezequiel Morales",
    Genero: 1,
    Edad: 28,
    AnioIngreso: 2020,
    AyudaFinanciera: 1,
    ColegioTecnico: 0,
    PromedioColegio: 5.1,
  },
  {
    IdAlumno: "ALU0015",
    Nombre: "Daniela Ortiz",
    Genero: 0,
    Edad: 20,
    AnioIngreso: 2023,
    AyudaFinanciera: 0,
    ColegioTecnico: 1,
    PromedioColegio: 8.3,
  },
  {
    IdAlumno: "ALU0016",
    Nombre: "Leandro Vargas",
    Genero: 1,
    Edad: 22,
    AnioIngreso: 2022,
    AyudaFinanciera: 0,
    ColegioTecnico: 0,
    PromedioColegio: 7.0,
  },
  {
    IdAlumno: "ALU0017",
    Nombre: "Juliana Molina",
    Genero: 0,
    Edad: 19,
    AnioIngreso: 2024,
    AyudaFinanciera: 1,
    ColegioTecnico: 0,
    PromedioColegio: 9.5,
  },
  {
    IdAlumno: "ALU0018",
    Nombre: "Ignacio Rojas",
    Genero: 1,
    Edad: 24,
    AnioIngreso: 2021,
    AyudaFinanciera: 0,
    ColegioTecnico: 1,
    PromedioColegio: 6.7,
  },
  {
    IdAlumno: "ALU0019",
    Nombre: "Carolina Silva",
    Genero: 0,
    Edad: 21,
    AnioIngreso: 2022,
    AyudaFinanciera: 1,
    ColegioTecnico: 0,
    PromedioColegio: 7.4,
  },
  {
    IdAlumno: "ALU0020",
    Nombre: "Rodrigo Acosta",
    Genero: 1,
    Edad: 27,
    AnioIngreso: 2020,
    AyudaFinanciera: 0,
    ColegioTecnico: 1,
    PromedioColegio: 5.8,
  },
];

router.get(
  "/",
  authenticate,
  authorize("admin", "coordinador", "docente"),
  (req, res) => {
    res.json(STUDENTS);
  },
);

router.get(
  "/:id",
  authenticate,
  authorize("admin", "coordinador", "docente"),
  (req, res) => {
    const student = STUDENTS.find((s) => s.IdAlumno === req.params.id);
    if (!student) {
      return res.status(404).json({ error: "Alumno no encontrado" });
    }
    res.json(student);
  },
);

module.exports = router;
